dataset: folder-mini_imagenet
root_path: ../../datasets/mini_imagenet
train:
  split: train
  image_size: 84
  normalization: False
  transform: null
  n_batch: 200
  n_episode: 4
  n_way: 5
  n_shot: 5
  n_query: 15
val:
  split: val
  image_size: 84
  normalization: False
  transform: null
  n_batch: 200
  n_episode: 4
  n_way: 5
  n_shot: 5
  n_query: 15
test:
  split: test
  image_size: 84
  normalization: False
  transform: null
  n_batch: 200
  n_episode: 4
  n_way: 5
  n_shot: 5
  n_query: 15

encoder: wide-convnet4
encoder_args:
  bn_args:
    track_running_stats: False
classifier: logistic

inner_args:
  n_step: 5
  encoder_lr: 0.01
  classifier_lr: 0.01
  first_order: False
  frozen:
    - bn

optimizer: adam
optimizer_args:
  lr: 0.001

epoch: 300
meta_autoencoder: False